const isLoggedIn = (req, res, next) => {
	try {
	} catch (error) {
		return next(error);
	}
};
